import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const promptFiles = [
  {
    filePath: resolve(rootDir, 'prompts/ai-summary.system.ja.txt'),
    exportName: 'AI_SUMMARY_SYSTEM_PROMPT',
  },
  {
    filePath: resolve(rootDir, 'prompts/ai-tags.system.ja.txt'),
    exportName: 'AI_TAGS_SYSTEM_PROMPT',
  },
]

const formatLiteral = (value) => JSON.stringify(value.trimEnd(), null, 2)

const output = [
  '// Generated by scripts/generate-prompts.mjs. Do not edit by hand.',
  '',
  ...promptFiles.flatMap(({ filePath, exportName }) => {
    const content = readFileSync(filePath, 'utf8')
    return [`export const ${exportName} = ${formatLiteral(content)} as const`, '']
  }),
].join('\n')

writeFileSync(resolve(rootDir, 'src/lib/ai-prompts.generated.ts'), `${output}\n`)
